### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by avishnyakov** [opsgenie/opsgenie-nodejs-sdk#15]
Hi team, is this project still alive and supported by OpsGenie?

**Comment by DanCarlyon** [comment]
@avishnyakov 

I don't believe so but you may want to check out this one: https://www.npmjs.com/package/opsgenie-sdk-revived

**Comment by prakhar-mudaiya** [comment]
@DanCarlyon  @avishnyakov . Yes, we have added incident api and Heartbeat API. we are also working on issue like User v2 which have been pointed out. This is currently supported by Opsgenie. Please raise any issue if you have any

**Comment by trabab** [comment]
As @prakhar-mudaiya has mentioned. We are planning to revive and add new functionalities to it. I hope we have addressed your answer, so closing this Issue. 

Please feel free to add more suggestions or let us know if you have any feature request in mind.
