### ISSUE TITLE
Version 0.4.4 not working at all

### ISSUE THREAD

**Issue by Always-Starter** [opsgenie/opsgenie-nodejs-sdk#22]
version 0.4.4 deleted alert file /resources/alert.js,
but it's still in use in opsgenie.js

![image](https://user-images.githubusercontent.com/7390027/104568693-5c111b80-568b-11eb-8940-9031c21a3aeb.png)

The following error will popup when I'm trying to import this package in my code

![image](https://user-images.githubusercontent.com/7390027/104568904-98dd1280-568b-11eb-95eb-91686d532379.png)

**Comment by AwolDes** [comment]
This is also happening for me, same error.

**Comment by mumblemaker** [comment]
Experienced the same. Looks like a reference to the Alert resource was left behind when Alertv2 was added. This change breaks any clean deployments. Provided fix in #24. Appreciated if someone can review and approve :)

**Comment by award1230** [comment]
bump

**Comment by insanicly** [comment]
Closed with 
https://github.com/opsgenie/opsgenie-nodejs-sdk/pull/24
https://github.com/opsgenie/opsgenie-nodejs-sdk/pull/25
